apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
        - name: shoppingapi
          image: shoppingarc.azurecr.io/shopppingapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
            - name: DatabaseSettings__DatabaseName
              value: shoppingdb
            - name: DatabaseSettings__CollectionName
              value: products
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  selector:
    app: shoppingapi
  ports:
    - protocol: TCP
      port: 5000